### ISSUE TITLE
FYI: Needed to include the file elsewhere as well

### ISSUE THREAD

**Issue by dogweather** [guilhermechapiewski/titanium-cache#1]
Hi,

Just a note. The readme says it needs to only be included, once, in the app.js. I did that. However, I found that I need to include it in my window's .js file to function.

**Comment by dogweather** [comment]
I get this error message: Result of expression 'Titanium.Cache' [undefined] is not an object. 

Hmm... but including the file twice does seem to start two expiration tasks.

**Comment by guilhermechapiewski** [comment]
Hey Robb,

This is weird....

Can you try ti include Cache under Ti.App.Cache and see what happens?

**Comment by dogweather** [comment]
Yep! That worked:
- Changed all references in cache.js to Ti.App.Cache.
- I'm now including the file only once, in my app.js.
- When I use the library, I reference it, e.g. as Ti.App.Cache.get().

**Comment by guilhermechapiewski** [comment]
Great!

Just changed the docs and code to use Ti.App.Cache.*

Thanks for your help!

**Comment by dogweather** [comment]
Cool. Weird that you didn't have this issue. Who knows... I'm making an
iPhone app, using SDK 1.2.2.
